
import "../styles/globals.css";
import Header from "@/components/layouts/Header";

import { Hind_Siliguri } from "next/font/google";

const hindSiliguri = Hind_Siliguri({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});




export const metadata = {
  title: "RYAN CLINIC",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased hindSiliguri.className`} >

        <Header />

        {children}



      </body>
    </html>
  );
}
